// Generated by scripts/manifest.mjs, do not edit.

/**
 * @typedef {{
 *   file: string
 *   sha256: string
 *   provenance: 'sigstore' | 'sha256-only'
 * }} Asset
 * @typedef {{ versions: Record<string, Record<string, Asset>> }} Manifest
 */

/** @type {Manifest} */
export const manifest = {
  versions: {
    '1.0.0': {
      'aarch64-apple-darwin': {
        file: 'gleam-v1.0.0-aarch64-apple-darwin.tar.gz',
        sha256:
          'f36d7e1f0c9a028e8203890f8dd56999de31d7ef88ee05ea74dd9ad986c4b3d8',
        provenance: 'sha256-only',
      },
      'aarch64-unknown-linux-musl': {
        file: 'gleam-v1.0.0-aarch64-unknown-linux-musl.tar.gz',
        sha256:
          'bc02ea3077c00dafba930b2b9c14990922a2ad16b3583b3bca0ce1c051c3db4f',
        provenance: 'sha256-only',
      },
      'x86_64-apple-darwin': {
        file: 'gleam-v1.0.0-x86_64-apple-darwin.tar.gz',
        sha256:
          '16a6784b5615258e0c22c502fac690c7e49a6bce11d617fd8b3d1ef5ce11bfe1',
        provenance: 'sha256-only',
      },
      'x86_64-pc-windows-msvc': {
        file: 'gleam-v1.0.0-x86_64-pc-windows-msvc.zip',
        sha256:
          '73c51ab8a0b889d66e17e4b52e7d6a078edea864e9b44efc8807c807bfdec765',
        provenance: 'sha256-only',
      },
      'x86_64-unknown-linux-musl': {
        file: 'gleam-v1.0.0-x86_64-unknown-linux-musl.tar.gz',
        sha256:
          '8f67909d90063cc4c0e025d8e020b0daa2f8ae8b4e4ca3214934c46378414a15',
        provenance: 'sha256-only',
      },
    },
    '1.1.0': {
      'aarch64-apple-darwin': {
        file: 'gleam-v1.1.0-aarch64-apple-darwin.tar.gz',
        sha256:
          '2dfd2bbd9786a5dd3e46a5fd77d4f3fde140617c262c9d6677ffb768d09cee46',
        provenance: 'sha256-only',
      },
      'aarch64-unknown-linux-musl': {
        file: 'gleam-v1.1.0-aarch64-unknown-linux-musl.tar.gz',
        sha256:
          'e7ec1e3d46c1afbd9d095970dcd5a5a8f5794494d4aaa458a9731f8f4b11b2f5',
        provenance: 'sha256-only',
      },
      'x86_64-apple-darwin': {
        file: 'gleam-v1.1.0-x86_64-apple-darwin.tar.gz',
        sha256:
          '8af188e495d43dd1ccdba496bf74082e60bc126486351aa6078f5ce48451923c',
        provenance: 'sha256-only',
      },
      'x86_64-pc-windows-msvc': {
        file: 'gleam-v1.1.0-x86_64-pc-windows-msvc.zip',
        sha256:
          '7fd786c5f20d4eaddef9dfe4fde2d6f86c91789cfdaf9cf8778d511d544c1ee8',
        provenance: 'sha256-only',
      },
      'x86_64-unknown-linux-musl': {
        file: 'gleam-v1.1.0-x86_64-unknown-linux-musl.tar.gz',
        sha256:
          '2e0f3f520586fa4c4531f90f80485eeaeba29c30428d9b5ecd732e15bb1cabe0',
        provenance: 'sha256-only',
      },
    },
    '1.2.0': {
      'aarch64-apple-darwin': {
        file: 'gleam-v1.2.0-aarch64-apple-darwin.tar.gz',
        sha256:
          '4acb36356cbf6de238a9d4292e7aabc951ff999cfcfd8ced444bd93fd67b90e5',
        provenance: 'sha256-only',
      },
      'aarch64-unknown-linux-musl': {
        file: 'gleam-v1.2.0-aarch64-unknown-linux-musl.tar.gz',
        sha256:
          '4a914b1bab1acd9de051ee0027fd20672286c52d3d12ae15e309124258018aee',
        provenance: 'sha256-only',
      },
      'x86_64-apple-darwin': {
        file: 'gleam-v1.2.0-x86_64-apple-darwin.tar.gz',
        sha256:
          'dfe3fba44cf2a9c39c82ee072b966a586495e8252a281c0b37d4600162abcf7f',
        provenance: 'sha256-only',
      },
      'x86_64-pc-windows-msvc': {
        file: 'gleam-v1.2.0-x86_64-pc-windows-msvc.zip',
        sha256:
          'c311a9bf61486411e992d8669b3155b0fb3b89966ecbf177e8042cfd1c2245b9',
        provenance: 'sha256-only',
      },
      'x86_64-unknown-linux-musl': {
        file: 'gleam-v1.2.0-x86_64-unknown-linux-musl.tar.gz',
        sha256:
          '6a053551a40719ae5994eb920c912b741ac3bc0181ef03f6d18b2c90e755027b',
        provenance: 'sha256-only',
      },
    },
    '1.2.1': {
      'aarch64-apple-darwin': {
        file: 'gleam-v1.2.1-aarch64-apple-darwin.tar.gz',
        sha256:
          '05a013110823efcc5f722da2123bce14d7acd49fe3b056702f250f58b4e7c578',
        provenance: 'sha256-only',
      },
      'aarch64-unknown-linux-musl': {
        file: 'gleam-v1.2.1-aarch64-unknown-linux-musl.tar.gz',
        sha256:
          '560ce633fed47b7e3d08b67c21da4c635cefbd0845b4b13d2afc7f423557fc2e',
        provenance: 'sha256-only',
      },
      'x86_64-apple-darwin': {
        file: 'gleam-v1.2.1-x86_64-apple-darwin.tar.gz',
        sha256:
          '1ef10a10533f965b257a34df7a5d4b3a352f010a5171c0773cde0d3859d69a17',
        provenance: 'sha256-only',
      },
      'x86_64-pc-windows-msvc': {
        file: 'gleam-v1.2.1-x86_64-pc-windows-msvc.zip',
        sha256:
          'd34d08f1d4a46198d7530d73f2d7f7b651005592de4a71e06b5ddea0f770084c',
        provenance: 'sha256-only',
      },
      'x86_64-unknown-linux-musl': {
        file: 'gleam-v1.2.1-x86_64-unknown-linux-musl.tar.gz',
        sha256:
          '5293251336a7419e8c9a424aca9ba0069266f23277365b82df2e3d0a67228498',
        provenance: 'sha256-only',
      },
    },
    '1.3.0': {
      'aarch64-apple-darwin': {
        file: 'gleam-v1.3.0-aarch64-apple-darwin.tar.gz',
        sha256:
          '3d0f7e11995b4d5d3c02febad06f0fcafd4333ed1aa7d386f60fdfc65dbd43c5',
        provenance: 'sha256-only',
      },
      'aarch64-unknown-linux-musl': {
        file: 'gleam-v1.3.0-aarch64-unknown-linux-musl.tar.gz',
        sha256:
          '9fe5537ffb3553b4092b6bec65d9f6daf70a63007a770d53b9c51bf4a56b1fb4',
        provenance: 'sha256-only',
      },
      'x86_64-apple-darwin': {
        file: 'gleam-v1.3.0-x86_64-apple-darwin.tar.gz',
        sha256:
          'c0ca1504f55db59627ec72dfa2367b42e039e6fe76411cc3e5e5560badd17141',
        provenance: 'sha256-only',
      },
      'x86_64-pc-windows-msvc': {
        file: 'gleam-v1.3.0-x86_64-pc-windows-msvc.zip',
        sha256:
          '0549e9ec4bbb9950005a632e47147c51026e03c1cd528f18bd9cce7eb953a613',
        provenance: 'sha256-only',
      },
      'x86_64-unknown-linux-musl': {
        file: 'gleam-v1.3.0-x86_64-unknown-linux-musl.tar.gz',
        sha256:
          '9fd56b4f69b99c5abf340efeee70df07d7e55775f618cf2f59932641aae478fa',
        provenance: 'sha256-only',
      },
    },
    '1.3.1': {
      'aarch64-apple-darwin': {
        file: 'gleam-v1.3.1-aarch64-apple-darwin.tar.gz',
        sha256:
          'a25ad674d0b7c36a68e30e1cd2232ae042d84cc0770fecb97f249080376346e6',
        provenance: 'sha256-only',
      },
      'aarch64-unknown-linux-musl': {
        file: 'gleam-v1.3.1-aarch64-unknown-linux-musl.tar.gz',
        sha256:
          'b41cdb63fa3056abac1abeda615d89a459b6f63ff6ad44a6b77c76cfc46d832b',
        provenance: 'sha256-only',
      },
      'x86_64-apple-darwin': {
        file: 'gleam-v1.3.1-x86_64-apple-darwin.tar.gz',
        sha256:
          '221f11a770ec09904e61758378bc639a97c1307071fbbc4deb160e93a7811b8c',
        provenance: 'sha256-only',
      },
      'x86_64-pc-windows-msvc': {
        file: 'gleam-v1.3.1-x86_64-pc-windows-msvc.zip',
        sha256:
          '11591c1a7174a98913f623374e71b543ef1517a015b19e0dd8e48a6065035b4f',
        provenance: 'sha256-only',
      },
      'x86_64-unknown-linux-musl': {
        file: 'gleam-v1.3.1-x86_64-unknown-linux-musl.tar.gz',
        sha256:
          '7ea732f927098d825e90d27c5361d497518d64eb74b4b3b875398a537a937dea',
        provenance: 'sha256-only',
      },
    },
    '1.3.2': {
      'aarch64-apple-darwin': {
        file: 'gleam-v1.3.2-aarch64-apple-darwin.tar.gz',
        sha256:
          '3a0567089bbd04c5de1b67364b9f879fecb93cd35791af75992f8e2a470e18ab',
        provenance: 'sha256-only',
      },
      'aarch64-unknown-linux-musl': {
        file: 'gleam-v1.3.2-aarch64-unknown-linux-musl.tar.gz',
        sha256:
          '60302574f9416d97602a1f9b203c0e2d7e7ae077fd5b34978cc6aecd07b00768',
        provenance: 'sha256-only',
      },
      'x86_64-apple-darwin': {
        file: 'gleam-v1.3.2-x86_64-apple-darwin.tar.gz',
        sha256:
          '8913d244e3b08a75abe6a77e5d8d2360a035ec8cbf39e40239dec884d0b8fc25',
        provenance: 'sha256-only',
      },
      'x86_64-pc-windows-msvc': {
        file: 'gleam-v1.3.2-x86_64-pc-windows-msvc.zip',
        sha256:
          '2932b184d591075f9f21799be14858947bef17129d2e3aa4abe0de9c779f8c94',
        provenance: 'sha256-only',
      },
      'x86_64-unknown-linux-musl': {
        file: 'gleam-v1.3.2-x86_64-unknown-linux-musl.tar.gz',
        sha256:
          '259197be528d6435fa43c4daf2f017572a63dd0ba2dddb044c7b1dd81beffb3f',
        provenance: 'sha256-only',
      },
    },
    '1.4.0': {
      'aarch64-apple-darwin': {
        file: 'gleam-v1.4.0-aarch64-apple-darwin.tar.gz',
        sha256:
          '6cd5169434aaa3b4cd295bc29b79da296675fd72f078f067ed9b2f81530d4ae2',
        provenance: 'sha256-only',
      },
      'aarch64-unknown-linux-musl': {
        file: 'gleam-v1.4.0-aarch64-unknown-linux-musl.tar.gz',
        sha256:
          'c7658094848997c29dff7a9bba38fe2e852ed2a691b5618a53c611cb59978b4b',
        provenance: 'sha256-only',
      },
      'x86_64-apple-darwin': {
        file: 'gleam-v1.4.0-x86_64-apple-darwin.tar.gz',
        sha256:
          '27b3641f21ea946ad75253102fda3f9d565dc27f39b511ab93e25cf33aeb67a1',
        provenance: 'sha256-only',
      },
      'x86_64-pc-windows-msvc': {
        file: 'gleam-v1.4.0-x86_64-pc-windows-msvc.zip',
        sha256:
          '4a6829eaf555d97a024d2f11a70c9c8ac96600798cbb9b5245e471960cc211b2',
        provenance: 'sha256-only',
      },
      'x86_64-unknown-linux-musl': {
        file: 'gleam-v1.4.0-x86_64-unknown-linux-musl.tar.gz',
        sha256:
          'a7bf11c514090b64209deeaa61ff874a1ccef863640da2aea8c6e859fcea09b6',
        provenance: 'sha256-only',
      },
    },
    '1.4.1': {
      'aarch64-apple-darwin': {
        file: 'gleam-v1.4.1-aarch64-apple-darwin.tar.gz',
        sha256:
          'cf5b2f956056038d5a23d6f17bb5ab17ffab460f07a2feb02f9d307e388f7557',
        provenance: 'sha256-only',
      },
      'aarch64-unknown-linux-musl': {
        file: 'gleam-v1.4.1-aarch64-unknown-linux-musl.tar.gz',
        sha256:
          '6724dd3a578d7463552525afa4a73cde1a0738793c0c4b55522c81505612e0cc',
        provenance: 'sha256-only',
      },
      'x86_64-apple-darwin': {
        file: 'gleam-v1.4.1-x86_64-apple-darwin.tar.gz',
        sha256:
          'b6a3adbdfe6fb3cd605580824b907c023d8b00da8550d682adcdd58915cc59ee',
        provenance: 'sha256-only',
      },
      'x86_64-pc-windows-msvc': {
        file: 'gleam-v1.4.1-x86_64-pc-windows-msvc.zip',
        sha256:
          'f579aa23fd8fe8d8abaa2abcc74aaec433383c3ea417b22e71c487ccb19ae11f',
        provenance: 'sha256-only',
      },
      'x86_64-unknown-linux-musl': {
        file: 'gleam-v1.4.1-x86_64-unknown-linux-musl.tar.gz',
        sha256:
          '5676b05892c35fc00b50580c16a25f91e844ec79418d31be98f62598d705053d',
        provenance: 'sha256-only',
      },
    },
    '1.5.0': {
      'aarch64-apple-darwin': {
        file: 'gleam-v1.5.0-aarch64-apple-darwin.tar.gz',
        sha256:
          '611f2a48bedf6c2fa5738b76e68b4572fc5958a54fe0eca9b0f4be89357baf96',
        provenance: 'sha256-only',
      },
      'aarch64-unknown-linux-musl': {
        file: 'gleam-v1.5.0-aarch64-unknown-linux-musl.tar.gz',
        sha256:
          '9d5fdfe815567541df1094ea3c9c0d5a900c4aa04f9442ee41ab498bb79001dc',
        provenance: 'sha256-only',
      },
      'x86_64-apple-darwin': {
        file: 'gleam-v1.5.0-x86_64-apple-darwin.tar.gz',
        sha256:
          'cc9de20ee29fa92ca7a656499fed471adb885a6b78a43611091ba8342efa996a',
        provenance: 'sha256-only',
      },
      'x86_64-pc-windows-msvc': {
        file: 'gleam-v1.5.0-x86_64-pc-windows-msvc.zip',
        sha256:
          '0ff8988266f4d4745e0558460899d7cfa9387ada6482a127ab0a7f9aa087db90',
        provenance: 'sha256-only',
      },
      'x86_64-unknown-linux-musl': {
        file: 'gleam-v1.5.0-x86_64-unknown-linux-musl.tar.gz',
        sha256:
          'abc87ce1f4b6508e3c780512ac30ec7f3edb2bccae9f0e93cc1ea7387b895eea',
        provenance: 'sha256-only',
      },
    },
    '1.5.1': {
      'aarch64-apple-darwin': {
        file: 'gleam-v1.5.1-aarch64-apple-darwin.tar.gz',
        sha256:
          '40e32cd343f9c99d78c3697582ac1098fb388369b3c258c5a585fd3dc2681c50',
        provenance: 'sha256-only',
      },
      'aarch64-unknown-linux-musl': {
        file: 'gleam-v1.5.1-aarch64-unknown-linux-musl.tar.gz',
        sha256:
          '2a8ed7275478d3f5d79bb59d8cf1277e44773ed52ec188d080fa24ad73040f16',
        provenance: 'sha256-only',
      },
      'x86_64-apple-darwin': {
        file: 'gleam-v1.5.1-x86_64-apple-darwin.tar.gz',
        sha256:
          'd8fb75292974f3fd20d13030e8c820878297cfb92d35075d1961d3d63f3bbedb',
        provenance: 'sha256-only',
      },
      'x86_64-pc-windows-msvc': {
        file: 'gleam-v1.5.1-x86_64-pc-windows-msvc.zip',
        sha256:
          'd2143d933a325c13f38ede263fc5ced8a0a87014e5509178b16065fcf5744cda',
        provenance: 'sha256-only',
      },
      'x86_64-unknown-linux-musl': {
        file: 'gleam-v1.5.1-x86_64-unknown-linux-musl.tar.gz',
        sha256:
          '5ef7cdf34951a1a488d523e3d32d175eda98d834ac428a1c8be7111d38593b0b',
        provenance: 'sha256-only',
      },
    },
    '1.6.0': {
      'aarch64-apple-darwin': {
        file: 'gleam-v1.6.0-aarch64-apple-darwin.tar.gz',
        sha256:
          'c3bcbd3809d4637d8acf91b1127d8eda43a84d3c4c2defa0bd5e295922d445a1',
        provenance: 'sha256-only',
      },
      'aarch64-unknown-linux-musl': {
        file: 'gleam-v1.6.0-aarch64-unknown-linux-musl.tar.gz',
        sha256:
          'fd2b8e1804a96a3ef2525e5475d5a2766e82f749524ebfa39fc24be7177a33b7',
        provenance: 'sha256-only',
      },
      'x86_64-apple-darwin': {
        file: 'gleam-v1.6.0-x86_64-apple-darwin.tar.gz',
        sha256:
          '2a7eed2dcf6591bcbb455bb0febf64a6fbd47167124ea0aabca0639354d322e0',
        provenance: 'sha256-only',
      },
      'x86_64-pc-windows-msvc': {
        file: 'gleam-v1.6.0-x86_64-pc-windows-msvc.zip',
        sha256:
          '08e1429888c27d36d0d77dde14b6179be68895fc3a8c494c811cd78508d9703f',
        provenance: 'sha256-only',
      },
      'x86_64-unknown-linux-musl': {
        file: 'gleam-v1.6.0-x86_64-unknown-linux-musl.tar.gz',
        sha256:
          'e3b15a669d1d8256b578774184b35d668bb492ac6429a135153fabae7146fdd7',
        provenance: 'sha256-only',
      },
    },
    '1.6.1': {
      'aarch64-apple-darwin': {
        file: 'gleam-v1.6.1-aarch64-apple-darwin.tar.gz',
        sha256:
          'bab247ba653e2ac549e0c7965aaddf902ee9551091ef5c8b234540d07f4f8b9b',
        provenance: 'sha256-only',
      },
      'aarch64-unknown-linux-musl': {
        file: 'gleam-v1.6.1-aarch64-unknown-linux-musl.tar.gz',
        sha256:
          '946cb3feeea59201915954c01b090da091f567c2f8c7eb9ee5acaac6e14fc46d',
        provenance: 'sha256-only',
      },
      'x86_64-apple-darwin': {
        file: 'gleam-v1.6.1-x86_64-apple-darwin.tar.gz',
        sha256:
          '9b5aea0cf7ef04e0761d314262e2574c9ad5099d11a4432ae437b0be11319d1f',
        provenance: 'sha256-only',
      },
      'x86_64-pc-windows-msvc': {
        file: 'gleam-v1.6.1-x86_64-pc-windows-msvc.zip',
        sha256:
          'b144cd2ebb6b634e194528591f3001f70dfef79914a8ef6caebe0368f6cfd743',
        provenance: 'sha256-only',
      },
      'x86_64-unknown-linux-musl': {
        file: 'gleam-v1.6.1-x86_64-unknown-linux-musl.tar.gz',
        sha256:
          '4a33864ce31535b601f73ac12c24b1dd659c0a267895a51815aec1af4f85dacc',
        provenance: 'sha256-only',
      },
    },
    '1.6.2': {
      'aarch64-apple-darwin': {
        file: 'gleam-v1.6.2-aarch64-apple-darwin.tar.gz',
        sha256:
          '036e6e3abf64baa871df94f95ae147b74c750e220bc70ccbcc3e6091352e24d8',
        provenance: 'sha256-only',
      },
      'aarch64-unknown-linux-musl': {
        file: 'gleam-v1.6.2-aarch64-unknown-linux-musl.tar.gz',
        sha256:
          'f14520c29ed0d5bf43d16a133ec658017b35db7c1261cc71407ee3ab3256faa7',
        provenance: 'sha256-only',
      },
      'x86_64-apple-darwin': {
        file: 'gleam-v1.6.2-x86_64-apple-darwin.tar.gz',
        sha256:
          'e78ae96489bdb3f022905dca88c4dfb6c73b39f9fb75684f768faf74423aeaed',
        provenance: 'sha256-only',
      },
      'x86_64-pc-windows-msvc': {
        file: 'gleam-v1.6.2-x86_64-pc-windows-msvc.zip',
        sha256:
          '1ade03272b6b2d98a7653ebdf729c363971a0af459d236fe44fcbe7469aa626e',
        provenance: 'sha256-only',
      },
      'x86_64-unknown-linux-musl': {
        file: 'gleam-v1.6.2-x86_64-unknown-linux-musl.tar.gz',
        sha256:
          '2fc67c48e892d3f37c37766a53c3f38048a97f616a7d80b0fd6e99659d5acc7f',
        provenance: 'sha256-only',
      },
    },
    '1.6.3': {
      'aarch64-apple-darwin': {
        file: 'gleam-v1.6.3-aarch64-apple-darwin.tar.gz',
        sha256:
          'b0a06ef7e8e12d441bdf0b66be82e1884bf25c45c3c4f18a47f0e9bd48d2ad0a',
        provenance: 'sha256-only',
      },
      'aarch64-unknown-linux-musl': {
        file: 'gleam-v1.6.3-aarch64-unknown-linux-musl.tar.gz',
        sha256:
          '14f429656fc52953ed9a4df0178e25ce3d00968b1ac1fd90de2e74b5dc525181',
        provenance: 'sha256-only',
      },
      'x86_64-apple-darwin': {
        file: 'gleam-v1.6.3-x86_64-apple-darwin.tar.gz',
        sha256:
          'b99d30a927c5350e03c92a614e3e041885653b54b7c01549672ffe60c33002e1',
        provenance: 'sha256-only',
      },
      'x86_64-pc-windows-msvc': {
        file: 'gleam-v1.6.3-x86_64-pc-windows-msvc.zip',
        sha256:
          '45bf2e8311aca0c3dc1162a6d5804a98ba3b52b1920365be295dfc8f92d43197',
        provenance: 'sha256-only',
      },
      'x86_64-unknown-linux-musl': {
        file: 'gleam-v1.6.3-x86_64-unknown-linux-musl.tar.gz',
        sha256:
          'db9c07b41d8aacf4cd7235efba438af1a5dadefd94f1a6e08534d247d883bc88',
        provenance: 'sha256-only',
      },
    },
    '1.7.0': {
      'aarch64-apple-darwin': {
        file: 'gleam-v1.7.0-aarch64-apple-darwin.tar.gz',
        sha256:
          'a65411fec8e47a618412770f6dbb2189b2c5cbb2419d5eef73d467563853cd8f',
        provenance: 'sha256-only',
      },
      'aarch64-unknown-linux-musl': {
        file: 'gleam-v1.7.0-aarch64-unknown-linux-musl.tar.gz',
        sha256:
          '516117f9ef9fb941fc8100c1dccd2fe87284d3c28295706b5ac46ff6ced72bc4',
        provenance: 'sha256-only',
      },
      'x86_64-apple-darwin': {
        file: 'gleam-v1.7.0-x86_64-apple-darwin.tar.gz',
        sha256:
          'b28c157de8f80f1f2eb8919ff9722ab969f8bc87c52dad26d0fbc1ae0b9937da',
        provenance: 'sha256-only',
      },
      'x86_64-pc-windows-msvc': {
        file: 'gleam-v1.7.0-x86_64-pc-windows-msvc.zip',
        sha256:
          '7e0ceeaca17ee51e71f13b0d3c9215e8c0552af2184aee20c2567dc49eeadc9c',
        provenance: 'sha256-only',
      },
      'x86_64-unknown-linux-musl': {
        file: 'gleam-v1.7.0-x86_64-unknown-linux-musl.tar.gz',
        sha256:
          'b5fc6e6b9b8e8ebeeda3b9be60503d93b409d437d9f4595b4d5c9e1449c14f49',
        provenance: 'sha256-only',
      },
    },
    '1.8.0': {
      'aarch64-apple-darwin': {
        file: 'gleam-v1.8.0-aarch64-apple-darwin.tar.gz',
        sha256:
          'ec30e8a6260bb9c8a5362160543a4f7fcbe20fdc3c00e63c34fe0c920cb15df2',
        provenance: 'sha256-only',
      },
      'aarch64-unknown-linux-musl': {
        file: 'gleam-v1.8.0-aarch64-unknown-linux-musl.tar.gz',
        sha256:
          '08472ef3da55d4e94f3edcad7725c8d1c392b42a72a39393cb6d446064a1926f',
        provenance: 'sha256-only',
      },
      'x86_64-apple-darwin': {
        file: 'gleam-v1.8.0-x86_64-apple-darwin.tar.gz',
        sha256:
          'b44f6664f6255164a39ab2bbf234896e3ab21674e6dafaca92c750be15c86de4',
        provenance: 'sha256-only',
      },
      'x86_64-pc-windows-msvc': {
        file: 'gleam-v1.8.0-x86_64-pc-windows-msvc.zip',
        sha256:
          '1e8f10475cc00976c8d6af37a42c3a1249d66d37dd392b9da4f9c9a6ae6e993d',
        provenance: 'sha256-only',
      },
      'x86_64-unknown-linux-musl': {
        file: 'gleam-v1.8.0-x86_64-unknown-linux-musl.tar.gz',
        sha256:
          'f1337f74939ed33aa3d730936b120d83097d6426d0be288719b0b4e2a9dc9ff5',
        provenance: 'sha256-only',
      },
    },
    '1.8.1': {
      'aarch64-apple-darwin': {
        file: 'gleam-v1.8.1-aarch64-apple-darwin.tar.gz',
        sha256:
          '03b086c576bcbb125f2c546750519940bccdd0a204e4b504505665a5aa26b468',
        provenance: 'sha256-only',
      },
      'aarch64-unknown-linux-musl': {
        file: 'gleam-v1.8.1-aarch64-unknown-linux-musl.tar.gz',
        sha256:
          '54beb327c7327bb60cc47754398720190af2a66cbb0be1ff7421adc02b50831d',
        provenance: 'sha256-only',
      },
      'x86_64-apple-darwin': {
        file: 'gleam-v1.8.1-x86_64-apple-darwin.tar.gz',
        sha256:
          'd5c4be0c33d1bdf691a09f4f810f8b8e20d0c62febd35192f81542d61ed2484a',
        provenance: 'sha256-only',
      },
      'x86_64-pc-windows-msvc': {
        file: 'gleam-v1.8.1-x86_64-pc-windows-msvc.zip',
        sha256:
          'a8b057ac1a963784a4044e9f81d90f716121474e42d8ce3e43f435c5ef63e032',
        provenance: 'sha256-only',
      },
      'x86_64-unknown-linux-musl': {
        file: 'gleam-v1.8.1-x86_64-unknown-linux-musl.tar.gz',
        sha256:
          '1d608de1238a771f99086d6cacc52e8c65560a64e9c1ed7b0518f05ec7a847a8',
        provenance: 'sha256-only',
      },
    },
    '1.9.0': {
      'aarch64-apple-darwin': {
        file: 'gleam-v1.9.0-aarch64-apple-darwin.tar.gz',
        sha256:
          'fe98e878715dbb5bcfeef356d99ca421581dde7170479840f35c2c10fdfaf086',
        provenance: 'sha256-only',
      },
      'aarch64-unknown-linux-musl': {
        file: 'gleam-v1.9.0-aarch64-unknown-linux-musl.tar.gz',
        sha256:
          '037536ee1eb3e183b1802721e073ef202779ea434f32b302b591a79f10db2894',
        provenance: 'sha256-only',
      },
      'x86_64-apple-darwin': {
        file: 'gleam-v1.9.0-x86_64-apple-darwin.tar.gz',
        sha256:
          '7e8e97017b4115761309f6c10d8c20f0a7f390e774cd05b38e39d8e9e7597949',
        provenance: 'sha256-only',
      },
      'x86_64-pc-windows-msvc': {
        file: 'gleam-v1.9.0-x86_64-pc-windows-msvc.zip',
        sha256:
          '0f4bab9dd369afa5daed5051c4b3f19dbb8f9591cf45be4d534f4998431e6c9d',
        provenance: 'sha256-only',
      },
      'x86_64-unknown-linux-musl': {
        file: 'gleam-v1.9.0-x86_64-unknown-linux-musl.tar.gz',
        sha256:
          '21f7c297c5a0feb541db3c55c6ba445e3c0c18b35af6fa6e956b43a2f0fef623',
        provenance: 'sha256-only',
      },
    },
    '1.9.1': {
      'aarch64-apple-darwin': {
        file: 'gleam-v1.9.1-aarch64-apple-darwin.tar.gz',
        sha256:
          'f96f41fe2ea875214e29d4d3b38be825453ed7b42cf489e5fa605ce689c25ff4',
        provenance: 'sha256-only',
      },
      'aarch64-unknown-linux-musl': {
        file: 'gleam-v1.9.1-aarch64-unknown-linux-musl.tar.gz',
        sha256:
          '5b29275d2e9ac603c71a4ece0eaedcb360997754dd7f98945d4cdda39dfbc4b9',
        provenance: 'sha256-only',
      },
      'x86_64-apple-darwin': {
        file: 'gleam-v1.9.1-x86_64-apple-darwin.tar.gz',
        sha256:
          'a922206f80cc0193ee4753423e5bf023d922b0d7c86600b0d1fb4b06f3712f4a',
        provenance: 'sha256-only',
      },
      'x86_64-pc-windows-msvc': {
        file: 'gleam-v1.9.1-x86_64-pc-windows-msvc.zip',
        sha256:
          'eb49e04852e27ea193f75cd2b16248244fb55b96a8b484c071ee63a8203dd0c9',
        provenance: 'sha256-only',
      },
      'x86_64-unknown-linux-musl': {
        file: 'gleam-v1.9.1-x86_64-unknown-linux-musl.tar.gz',
        sha256:
          'e8757a6585b0d6dcd0718c3ddd4a847a4c906ef6cea7071a4e9abd2242ebbc75',
        provenance: 'sha256-only',
      },
    },
    '1.10.0': {
      'aarch64-apple-darwin': {
        file: 'gleam-v1.10.0-aarch64-apple-darwin.tar.gz',
        sha256:
          '90d8717505f14b925879432e177708550a5dd29c9a620e085f21f0ad753cc19a',
        provenance: 'sigstore',
      },
      'aarch64-unknown-linux-musl': {
        file: 'gleam-v1.10.0-aarch64-unknown-linux-musl.tar.gz',
        sha256:
          '15b528574f31f021bff7232c2fb851c686c369c67e96aedac04636b04094ac94',
        provenance: 'sigstore',
      },
      'x86_64-apple-darwin': {
        file: 'gleam-v1.10.0-x86_64-apple-darwin.tar.gz',
        sha256:
          'e31bbb2820ddfe2e7e37829d7c218ab357e0f6efb4b43f2c0ad5c277fd0ef787',
        provenance: 'sigstore',
      },
      'x86_64-pc-windows-msvc': {
        file: 'gleam-v1.10.0-x86_64-pc-windows-msvc.zip',
        sha256:
          '244dc8b008f1d11f436df7691c46260eb2e6006c8def748968a161948aeead0e',
        provenance: 'sigstore',
      },
      'x86_64-unknown-linux-musl': {
        file: 'gleam-v1.10.0-x86_64-unknown-linux-musl.tar.gz',
        sha256:
          '6ea95309e39e3abf56fe9a361dd079d502b5a944f8612d909d7f56c2fdc10a71',
        provenance: 'sigstore',
      },
    },
    '1.11.0': {
      'aarch64-apple-darwin': {
        file: 'gleam-v1.11.0-aarch64-apple-darwin.tar.gz',
        sha256:
          '888abc5aba9286c288f8eacd769911b44c01d9c9ce3085f0b915562647a986b2',
        provenance: 'sigstore',
      },
      'aarch64-pc-windows-msvc': {
        file: 'gleam-v1.11.0-aarch64-pc-windows-msvc.zip',
        sha256:
          '24d2f49e1443f4fc1c65f096c6e6d3ca608af0e771d0bb3666cac7cdfd108048',
        provenance: 'sigstore',
      },
      'aarch64-unknown-linux-musl': {
        file: 'gleam-v1.11.0-aarch64-unknown-linux-musl.tar.gz',
        sha256:
          '4c3359805cab2cb89b47a35c3c2f559df53b3c545251a6af3ba6042437aa464c',
        provenance: 'sigstore',
      },
      'x86_64-apple-darwin': {
        file: 'gleam-v1.11.0-x86_64-apple-darwin.tar.gz',
        sha256:
          'adf779f52ba1b8e33bc327b8c9f695e9617bec24145c4d44e723695bd17c472d',
        provenance: 'sigstore',
      },
      'x86_64-pc-windows-msvc': {
        file: 'gleam-v1.11.0-x86_64-pc-windows-msvc.zip',
        sha256:
          '4530dad4e10f5cc888b92b9f11729a69f436b95e3789bf907f6437810ba73171',
        provenance: 'sigstore',
      },
      'x86_64-unknown-linux-musl': {
        file: 'gleam-v1.11.0-x86_64-unknown-linux-musl.tar.gz',
        sha256:
          '19a6a100bf620686fe90a52d31569d4b0a4052ae6a270d08862019f9d3604675',
        provenance: 'sigstore',
      },
    },
    '1.11.1': {
      'aarch64-apple-darwin': {
        file: 'gleam-v1.11.1-aarch64-apple-darwin.tar.gz',
        sha256:
          'a2d492592d86539b1f51ae81f344dff71870b23479bf4d00d78512c6f9eaf1e5',
        provenance: 'sigstore',
      },
      'aarch64-pc-windows-msvc': {
        file: 'gleam-v1.11.1-aarch64-pc-windows-msvc.zip',
        sha256:
          'a409e9502dc20a427c118bb9ce64afeb8b78ab5652bf6cce3759ab7327ba3c93',
        provenance: 'sigstore',
      },
      'aarch64-unknown-linux-musl': {
        file: 'gleam-v1.11.1-aarch64-unknown-linux-musl.tar.gz',
        sha256:
          '22d4c9299f57f712210df7f48d1c84f99f13abfd9e067a6b290abfdab384161d',
        provenance: 'sigstore',
      },
      'x86_64-apple-darwin': {
        file: 'gleam-v1.11.1-x86_64-apple-darwin.tar.gz',
        sha256:
          'f250284e4998f4e7d274d60f8d4f9d5d5cf1519a86bd21065ba77dbff6065054',
        provenance: 'sigstore',
      },
      'x86_64-pc-windows-msvc': {
        file: 'gleam-v1.11.1-x86_64-pc-windows-msvc.zip',
        sha256:
          '1cb54473bed54d74e213f993a7f269ed27afa761d693be681b9bf1a3e618d4d5',
        provenance: 'sigstore',
      },
      'x86_64-unknown-linux-musl': {
        file: 'gleam-v1.11.1-x86_64-unknown-linux-musl.tar.gz',
        sha256:
          '31649fab05f982c51d7553cc4a2d3e615ee49348f7162fe75d48f71331618033',
        provenance: 'sigstore',
      },
    },
    '1.12.0': {
      'aarch64-apple-darwin': {
        file: 'gleam-v1.12.0-aarch64-apple-darwin.tar.gz',
        sha256:
          '885396e845fbbc014253dd95da493439b785641022fb92c45657b2b936cf317f',
        provenance: 'sigstore',
      },
      'aarch64-pc-windows-msvc': {
        file: 'gleam-v1.12.0-aarch64-pc-windows-msvc.zip',
        sha256:
          '44e820854af78a4a0daaa3282524e87f12c418bd76f1999869ec10fb0b6aec76',
        provenance: 'sigstore',
      },
      'aarch64-unknown-linux-musl': {
        file: 'gleam-v1.12.0-aarch64-unknown-linux-musl.tar.gz',
        sha256:
          'eb9707e42e452d5bbfb48b12d81571a098238a5afb4b7d16c1d07df7089e2bde',
        provenance: 'sigstore',
      },
      'x86_64-apple-darwin': {
        file: 'gleam-v1.12.0-x86_64-apple-darwin.tar.gz',
        sha256:
          'fca2a8cf5424cfa096710c191bbf8c02b635ed0e6c0e2ed38b95eba5e8df0302',
        provenance: 'sigstore',
      },
      'x86_64-pc-windows-msvc': {
        file: 'gleam-v1.12.0-x86_64-pc-windows-msvc.zip',
        sha256:
          '24e89e4f8bdb5a80ed214f6d57d9118a43ba3a339a8d1831b2975808a4988648',
        provenance: 'sigstore',
      },
      'x86_64-unknown-linux-musl': {
        file: 'gleam-v1.12.0-x86_64-unknown-linux-musl.tar.gz',
        sha256:
          '039a87bd7294d3cfd2425f56e8ffef508b170ecec42e760806833fb1e0319d49',
        provenance: 'sigstore',
      },
    },
    '1.13.0': {
      'aarch64-apple-darwin': {
        file: 'gleam-v1.13.0-aarch64-apple-darwin.tar.gz',
        sha256:
          '2398d1a130b1bb406bdb4a5c2cea2dc9867c677cf48b3d6c45eb200a653dbb36',
        provenance: 'sigstore',
      },
      'aarch64-pc-windows-msvc': {
        file: 'gleam-v1.13.0-aarch64-pc-windows-msvc.zip',
        sha256:
          '55956ac4358dd14874089f9726fc133d7765a53f73921e40fc64319655a0eb63',
        provenance: 'sigstore',
      },
      'aarch64-unknown-linux-musl': {
        file: 'gleam-v1.13.0-aarch64-unknown-linux-musl.tar.gz',
        sha256:
          '7f45fd9b9cce8106851fb1c476a58193e5cca456cf06efd784b39680f839da1e',
        provenance: 'sigstore',
      },
      'x86_64-apple-darwin': {
        file: 'gleam-v1.13.0-x86_64-apple-darwin.tar.gz',
        sha256:
          '858ec1297a3f5770324fb49ed0461b0c15c29bd3fe6e636e390f2e249d86a24a',
        provenance: 'sigstore',
      },
      'x86_64-pc-windows-msvc': {
        file: 'gleam-v1.13.0-x86_64-pc-windows-msvc.zip',
        sha256:
          'a59358ebba1abd10d50593a1dff88c0c4c16dc97566d097dc724788458794128',
        provenance: 'sigstore',
      },
      'x86_64-unknown-linux-musl': {
        file: 'gleam-v1.13.0-x86_64-unknown-linux-musl.tar.gz',
        sha256:
          '8b372488e5ccaa54d8acc2feb9852c9e7916e480566049edd565caa1d8c74eec',
        provenance: 'sigstore',
      },
    },
    '1.14.0': {
      'aarch64-apple-darwin': {
        file: 'gleam-v1.14.0-aarch64-apple-darwin.tar.gz',
        sha256:
          '81a7c879ff2ebd0d6a4831f92a738542e21148784ba6cc1aa1c3f726f36b0c22',
        provenance: 'sigstore',
      },
      'aarch64-pc-windows-msvc': {
        file: 'gleam-v1.14.0-aarch64-pc-windows-msvc.zip',
        sha256:
          '52863befce8f698ce266848e7928d96b964f77ce89fb8e57a83684f0b678aa85',
        provenance: 'sigstore',
      },
      'aarch64-unknown-linux-musl': {
        file: 'gleam-v1.14.0-aarch64-unknown-linux-musl.tar.gz',
        sha256:
          '16371f8e3b45303d240758fe07f4adcb0fe444edf2f82312a24451323869730c',
        provenance: 'sigstore',
      },
      'x86_64-apple-darwin': {
        file: 'gleam-v1.14.0-x86_64-apple-darwin.tar.gz',
        sha256:
          '809c9a0e2e440c62554ff5cf5c2c38a961d25b98197313dc4b73e6dea88f104d',
        provenance: 'sigstore',
      },
      'x86_64-pc-windows-msvc': {
        file: 'gleam-v1.14.0-x86_64-pc-windows-msvc.zip',
        sha256:
          '0531746b964de611da660c4e65a635dc0f7a4e9147e4b2e89b8c58ec316501b8',
        provenance: 'sigstore',
      },
      'x86_64-unknown-linux-musl': {
        file: 'gleam-v1.14.0-x86_64-unknown-linux-musl.tar.gz',
        sha256:
          '5dc66abbf3eb80f209f1c261ecfc44dc1404dd8ac503e483369d37182a4fcce8',
        provenance: 'sigstore',
      },
    },
    '1.15.0': {
      'aarch64-apple-darwin': {
        file: 'gleam-v1.15.0-aarch64-apple-darwin.tar.gz',
        sha256:
          'aa440d698f50374d3c908dd8e3ab1d62ad9b58912cd9e47924212239f76f65ef',
        provenance: 'sigstore',
      },
      'aarch64-pc-windows-msvc': {
        file: 'gleam-v1.15.0-aarch64-pc-windows-msvc.zip',
        sha256:
          'ef7b1804b8b33840a8e9f6a042fb9761edd8d0d22cb68398d2406a028f9b6058',
        provenance: 'sigstore',
      },
      'aarch64-unknown-linux-musl': {
        file: 'gleam-v1.15.0-aarch64-unknown-linux-musl.tar.gz',
        sha256:
          '72aae823719c85f6daf0b01003bbe1a33d6a120d2c30c5a7543bd4dea69869a8',
        provenance: 'sigstore',
      },
      'x86_64-apple-darwin': {
        file: 'gleam-v1.15.0-x86_64-apple-darwin.tar.gz',
        sha256:
          'd5362d30830646c0706f3a42cb0dc86e71a4371edf274f4db172f12e937bfc07',
        provenance: 'sigstore',
      },
      'x86_64-pc-windows-msvc': {
        file: 'gleam-v1.15.0-x86_64-pc-windows-msvc.zip',
        sha256:
          'df087eca557d2c5a554ae9d45a42f9d1583541feba2818d9088f50cc9523783c',
        provenance: 'sigstore',
      },
      'x86_64-unknown-linux-musl': {
        file: 'gleam-v1.15.0-x86_64-unknown-linux-musl.tar.gz',
        sha256:
          'b941e256b65630f89ae0d488b9681ae2f3e800a6a22a460ac334d62cd1a10ba3',
        provenance: 'sigstore',
      },
    },
    '1.15.1': {
      'aarch64-apple-darwin': {
        file: 'gleam-v1.15.1-aarch64-apple-darwin.tar.gz',
        sha256:
          '07574517355767975715763faf0c6dfe48138562e4558222f236b046a99e7539',
        provenance: 'sigstore',
      },
      'aarch64-pc-windows-msvc': {
        file: 'gleam-v1.15.1-aarch64-pc-windows-msvc.zip',
        sha256:
          '4c30be594383db32da5aaa1bc84904004d05659712ff0f36f969999e6596d03c',
        provenance: 'sigstore',
      },
      'aarch64-unknown-linux-musl': {
        file: 'gleam-v1.15.1-aarch64-unknown-linux-musl.tar.gz',
        sha256:
          'a73fa3a5b585a971f295d536d4902e8a33428d2167015dcbe031a90989b9fdb6',
        provenance: 'sigstore',
      },
      'x86_64-apple-darwin': {
        file: 'gleam-v1.15.1-x86_64-apple-darwin.tar.gz',
        sha256:
          '224aa038e09d7de9341b0b6f1ca81d00d5d85cc95b91af9a6311f041841c5815',
        provenance: 'sigstore',
      },
      'x86_64-pc-windows-msvc': {
        file: 'gleam-v1.15.1-x86_64-pc-windows-msvc.zip',
        sha256:
          'c3a79b88dc2eeeaff7d9d38a581fbbc4a89e0cbccb17378ee4e3ffedd00c21e8',
        provenance: 'sigstore',
      },
      'x86_64-unknown-linux-musl': {
        file: 'gleam-v1.15.1-x86_64-unknown-linux-musl.tar.gz',
        sha256:
          'e7013cc57334a16816263dfff9a35c8ab3797fe65f1dcb2ae67a4a688bda52d4',
        provenance: 'sigstore',
      },
    },
    '1.15.2': {
      'aarch64-apple-darwin': {
        file: 'gleam-v1.15.2-aarch64-apple-darwin.tar.gz',
        sha256:
          '89bf1556608bffd0e02fd741c3716e6ac20efb5a214631853e273f2faea44d94',
        provenance: 'sigstore',
      },
      'aarch64-pc-windows-msvc': {
        file: 'gleam-v1.15.2-aarch64-pc-windows-msvc.zip',
        sha256:
          'f932b731a424115f8518a0d15c73a19446444fb0cabf052e279e3acad2cc7c2b',
        provenance: 'sigstore',
      },
      'aarch64-unknown-linux-musl': {
        file: 'gleam-v1.15.2-aarch64-unknown-linux-musl.tar.gz',
        sha256:
          '05bb422b9870a887160e2af6ae1b6e221bfc133ffbb617738e98d10eb0a169d1',
        provenance: 'sigstore',
      },
      'x86_64-apple-darwin': {
        file: 'gleam-v1.15.2-x86_64-apple-darwin.tar.gz',
        sha256:
          '544c2520cb17d56d234d2f8c250d7072e09d0b3369876e056ce4479ec6e0c698',
        provenance: 'sigstore',
      },
      'x86_64-pc-windows-msvc': {
        file: 'gleam-v1.15.2-x86_64-pc-windows-msvc.zip',
        sha256:
          '56947258b0a9561322faea63f8bcf63c19ea60494f9f15ab99e36961dfbab42c',
        provenance: 'sigstore',
      },
      'x86_64-unknown-linux-musl': {
        file: 'gleam-v1.15.2-x86_64-unknown-linux-musl.tar.gz',
        sha256:
          'b9cf8201981f58c122fc4f953d85f278e7edaa26faa0f3853299cabfe1b7c9dc',
        provenance: 'sigstore',
      },
    },
    '1.15.3': {
      'aarch64-apple-darwin': {
        file: 'gleam-v1.15.3-aarch64-apple-darwin.tar.gz',
        sha256:
          '818bccda59a887e788efa91ae8a31da972dfc3519dcfbcb4f35d4b8ddfe8caeb',
        provenance: 'sigstore',
      },
      'aarch64-pc-windows-msvc': {
        file: 'gleam-v1.15.3-aarch64-pc-windows-msvc.zip',
        sha256:
          '8b90b296c98bf599c3b16f323a7ddc6dcfc9bff8dcd50d4d68434a2222124d6e',
        provenance: 'sigstore',
      },
      'aarch64-unknown-linux-musl': {
        file: 'gleam-v1.15.3-aarch64-unknown-linux-musl.tar.gz',
        sha256:
          'baf6104c5388fb5a166a5780f6d9bff8b479430cfa0c28c70eb59f9bc0f3de77',
        provenance: 'sigstore',
      },
      'x86_64-apple-darwin': {
        file: 'gleam-v1.15.3-x86_64-apple-darwin.tar.gz',
        sha256:
          '1dea671242326fd0f29be1a597a5a6a1f6fb41bc59302e21ffbdfeb55f545964',
        provenance: 'sigstore',
      },
      'x86_64-pc-windows-msvc': {
        file: 'gleam-v1.15.3-x86_64-pc-windows-msvc.zip',
        sha256:
          'a89e129acd230b8a438d2a129447014dc684d29b19dd305e58eada51159cab31',
        provenance: 'sigstore',
      },
      'x86_64-unknown-linux-musl': {
        file: 'gleam-v1.15.3-x86_64-unknown-linux-musl.tar.gz',
        sha256:
          '0f018e243e934a850ecddc9e3bcdba304b48574bc4881b61a3f423038f882198',
        provenance: 'sigstore',
      },
    },
    '1.15.4': {
      'aarch64-apple-darwin': {
        file: 'gleam-v1.15.4-aarch64-apple-darwin.tar.gz',
        sha256:
          '74b03d43916d0147ce75ac909bb3636b8045c09303ec38256ebea5138fb2218f',
        provenance: 'sigstore',
      },
      'aarch64-pc-windows-msvc': {
        file: 'gleam-v1.15.4-aarch64-pc-windows-msvc.zip',
        sha256:
          '2f5793598327f9530a3cef61d21d3095ffb8cf282096c6216bb4af3c99a3b2b7',
        provenance: 'sigstore',
      },
      'aarch64-unknown-linux-musl': {
        file: 'gleam-v1.15.4-aarch64-unknown-linux-musl.tar.gz',
        sha256:
          'f145cc26ae0906d287f0c8dacede6a405a2dd888877d901dff64c288a2f1ec1f',
        provenance: 'sigstore',
      },
      'x86_64-apple-darwin': {
        file: 'gleam-v1.15.4-x86_64-apple-darwin.tar.gz',
        sha256:
          '7624faf7ea4f401be7800aba612ba51d97bb86dd0aa9b7c769802860a9e524a4',
        provenance: 'sigstore',
      },
      'x86_64-pc-windows-msvc': {
        file: 'gleam-v1.15.4-x86_64-pc-windows-msvc.zip',
        sha256:
          '10d39e079780f1040606e51d4da837b90df449c168216e2141b6ae2f867fd7c3',
        provenance: 'sigstore',
      },
      'x86_64-unknown-linux-musl': {
        file: 'gleam-v1.15.4-x86_64-unknown-linux-musl.tar.gz',
        sha256:
          '7c93bcd951e4aa59ffcaf1791e112ccc83127cc4cd2f16820b31647ce521f4c7',
        provenance: 'sigstore',
      },
    },
    '1.16.0': {
      'aarch64-apple-darwin': {
        file: 'gleam-v1.16.0-aarch64-apple-darwin.tar.gz',
        sha256:
          'a1a2bb4611d379ad8d95c6ef5d0ba8e8e8a8ee1ec9e9619f9198898096eb0d41',
        provenance: 'sigstore',
      },
      'aarch64-pc-windows-msvc': {
        file: 'gleam-v1.16.0-aarch64-pc-windows-msvc.zip',
        sha256:
          '249730535ff673a8ff70d96ee4eafe2303f699d305ca3ec84a654b033bb1e74b',
        provenance: 'sigstore',
      },
      'aarch64-unknown-linux-musl': {
        file: 'gleam-v1.16.0-aarch64-unknown-linux-musl.tar.gz',
        sha256:
          'e7af3677a04a1b88f19896b7b351f407784c62e97078fe680f90a91a5da162d8',
        provenance: 'sigstore',
      },
      'x86_64-apple-darwin': {
        file: 'gleam-v1.16.0-x86_64-apple-darwin.tar.gz',
        sha256:
          '25a76ae6299f8e45c10da6fc7b3592062c3fe9bd45a29078e197a975c590b327',
        provenance: 'sigstore',
      },
      'x86_64-pc-windows-msvc': {
        file: 'gleam-v1.16.0-x86_64-pc-windows-msvc.zip',
        sha256:
          '72ea481f45d819536b068e31b601c96747aeaf44add97c9855d5c9bca2367175',
        provenance: 'sigstore',
      },
      'x86_64-unknown-linux-musl': {
        file: 'gleam-v1.16.0-x86_64-unknown-linux-musl.tar.gz',
        sha256:
          '1ca1183719a32c2cfb15a845ff6192bd2cb4eaf4d8913bfad9662349f8d9a7ff',
        provenance: 'sigstore',
      },
    },
    '1.17.0': {
      'aarch64-apple-darwin': {
        file: 'gleam-v1.17.0-aarch64-apple-darwin.tar.gz',
        sha256:
          '20e5839b9b88475e3ab0bea64f353b4d5aa6be8c91215b8f91cf46cb51f36d5e',
        provenance: 'sigstore',
      },
      'aarch64-pc-windows-msvc': {
        file: 'gleam-v1.17.0-aarch64-pc-windows-msvc.zip',
        sha256:
          'b65b04b09098f0dfa2b887432b6438ddc0a8bf86d46a99df49122ba368d7d84e',
        provenance: 'sigstore',
      },
      'aarch64-unknown-linux-musl': {
        file: 'gleam-v1.17.0-aarch64-unknown-linux-musl.tar.gz',
        sha256:
          '2ddc2017f8c2112bf6a58bc662dc8c59a75814165ae593230368509e890ee8ca',
        provenance: 'sigstore',
      },
      'x86_64-apple-darwin': {
        file: 'gleam-v1.17.0-x86_64-apple-darwin.tar.gz',
        sha256:
          '37def38d81056c81b029d7fc0d28c91dda34f55c5ca5ce82562b01b518bdb66d',
        provenance: 'sigstore',
      },
      'x86_64-pc-windows-msvc': {
        file: 'gleam-v1.17.0-x86_64-pc-windows-msvc.zip',
        sha256:
          '4790b0e35c6acf441eac0746130417913eb4b099d7d10d0c843792c69886bbbe',
        provenance: 'sigstore',
      },
      'x86_64-unknown-linux-musl': {
        file: 'gleam-v1.17.0-x86_64-unknown-linux-musl.tar.gz',
        sha256:
          'c0d1eaadac40c88ac93ea45fc150f6363f4ceb8c925b5ac90f371b1665613cc4',
        provenance: 'sigstore',
      },
    },
    '1.18.0': {
      'aarch64-apple-darwin': {
        file: 'gleam-v1.18.0-aarch64-apple-darwin.tar.gz',
        sha256:
          '264fbbb76510f0960b417c8071f8b5c24b07bd0d00efe8117517c688681b7d62',
        provenance: 'sigstore',
      },
      'aarch64-pc-windows-msvc': {
        file: 'gleam-v1.18.0-aarch64-pc-windows-msvc.zip',
        sha256:
          'f8c8c138fbef77e5221057b593c9d74efef08e6dcbd3ada76962c8631a04b558',
        provenance: 'sigstore',
      },
      'aarch64-unknown-linux-musl': {
        file: 'gleam-v1.18.0-aarch64-unknown-linux-musl.tar.gz',
        sha256:
          'e1745be9ab3c1680f3dc22b11f6550c818b8d7355f4aa93fa56339e2040eba54',
        provenance: 'sigstore',
      },
      'x86_64-apple-darwin': {
        file: 'gleam-v1.18.0-x86_64-apple-darwin.tar.gz',
        sha256:
          'bf495ce67329d42f8a34f47cfca578ca548d240d68beddbb67745b712d802e7d',
        provenance: 'sigstore',
      },
      'x86_64-pc-windows-msvc': {
        file: 'gleam-v1.18.0-x86_64-pc-windows-msvc.zip',
        sha256:
          'b98eb7c9d4f0b722128c57bf62400f9f49f78795653e873190d30094f0b8e7b1',
        provenance: 'sigstore',
      },
      'x86_64-unknown-linux-musl': {
        file: 'gleam-v1.18.0-x86_64-unknown-linux-musl.tar.gz',
        sha256:
          'ad039b18271fa3a59d50adb0eeca88e0ce2da106d4342d99591f39da767a7330',
        provenance: 'sigstore',
      },
    },
    '1.18.1': {
      'aarch64-apple-darwin': {
        file: 'gleam-v1.18.1-aarch64-apple-darwin.tar.gz',
        sha256:
          '1aae21fd5c70b89e0972427934a13b33886efa7f08bf428e1baee5ebd10d1753',
        provenance: 'sigstore',
      },
      'aarch64-pc-windows-msvc': {
        file: 'gleam-v1.18.1-aarch64-pc-windows-msvc.zip',
        sha256:
          '2fa5f4374fa565e320a47520ec92eeaf933622e698ce216e5af2b95054f8fcbb',
        provenance: 'sigstore',
      },
      'aarch64-unknown-linux-musl': {
        file: 'gleam-v1.18.1-aarch64-unknown-linux-musl.tar.gz',
        sha256:
          'ea08a64846677f36da7f2e9163c4393dd9a9dee814d13a8fb28fbe7dcbf32f6d',
        provenance: 'sigstore',
      },
      'x86_64-apple-darwin': {
        file: 'gleam-v1.18.1-x86_64-apple-darwin.tar.gz',
        sha256:
          'bd5017621ad5b7509568d5d004a2c1d5fb8f70e7555b1abdb62f35908c0ee1b6',
        provenance: 'sigstore',
      },
      'x86_64-pc-windows-msvc': {
        file: 'gleam-v1.18.1-x86_64-pc-windows-msvc.zip',
        sha256:
          '1702b597e27486be7eb5fd8d3624eeca7ae5e183009e01ae2550b8a9b2a96a44',
        provenance: 'sigstore',
      },
      'x86_64-unknown-linux-musl': {
        file: 'gleam-v1.18.1-x86_64-unknown-linux-musl.tar.gz',
        sha256:
          '4955a38c2e8c99457458e2471472ccd5ee3c45bd7637a315ce33bccf0dd75d9e',
        provenance: 'sigstore',
      },
    },
    '1.19.0': {
      'aarch64-apple-darwin': {
        file: 'gleam-v1.19.0-aarch64-apple-darwin.tar.gz',
        sha256:
          '7abff14c1acc7eb725ef4883539c6b48de72b58593b331cac0ff23e0a5f068c7',
        provenance: 'sigstore',
      },
      'aarch64-pc-windows-msvc': {
        file: 'gleam-v1.19.0-aarch64-pc-windows-msvc.zip',
        sha256:
          'd2600f780cb807f83ef473f68cf1039813bad6528c55f50395072516dcf63bb0',
        provenance: 'sigstore',
      },
      'aarch64-unknown-linux-musl': {
        file: 'gleam-v1.19.0-aarch64-unknown-linux-musl.tar.gz',
        sha256:
          'b7677e3763eb7a6752e37f9a7f6f9451419cab5ccdbf4a41814a81356c58cc1d',
        provenance: 'sigstore',
      },
      'x86_64-apple-darwin': {
        file: 'gleam-v1.19.0-x86_64-apple-darwin.tar.gz',
        sha256:
          '28bd942b47da84b8b870d4ed56e31972375b4c8f7455716086dfba5be7f3e687',
        provenance: 'sigstore',
      },
      'x86_64-pc-windows-msvc': {
        file: 'gleam-v1.19.0-x86_64-pc-windows-msvc.zip',
        sha256:
          '47cc9eed05ec44526ee610c40f3103d48a4b558a442b5c5e085d21386ab8bb23',
        provenance: 'sigstore',
      },
      'x86_64-unknown-linux-musl': {
        file: 'gleam-v1.19.0-x86_64-unknown-linux-musl.tar.gz',
        sha256:
          '6083148cb404460810afe35e7878527e58fd2512dd79a76b47d59723815753be',
        provenance: 'sigstore',
      },
    },
  },
}
